name: Run test case

on: [push, pull_request]

jobs:

    run_test_case:

        runs-on: ubuntu-latest

        strategy:
          matrix:
            otp:
              - erlang:23.0.3
              - erlang:22.3
              - erlang:21.3

        container:
            image: ${{ matrix.otp }}

        steps:
        - uses: actions/checkout@v1
        - name: Code dialyzer
          run: |
            make xref
            make dialyzer
        - name: Run tests
          run: |
            make eunit
            make ct
            make cover
        - name: Coveralls
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
              make coveralls
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: _build/test/logs
